//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS.Service.WCFClient.ATS.WCFClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/ATS.Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ATS.Service.WCFClient.ATS.WCFClient.Agent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ATS.Service.WCFClient.ATS.WCFClient.Staff))]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeAddress {
            get {
                return this.HomeAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeAddressField, value) != true)) {
                    this.HomeAddressField = value;
                    this.RaisePropertyChanged("HomeAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonName {
            get {
                return this.PersonNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonNameField, value) != true)) {
                    this.PersonNameField = value;
                    this.RaisePropertyChanged("PersonName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Agent", Namespace="http://schemas.datacontract.org/2004/07/ATS.Service")]
    [System.SerializableAttribute()]
    public partial class Agent : ATS.Service.WCFClient.ATS.WCFClient.Person {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Staff", Namespace="http://schemas.datacontract.org/2004/07/ATS.Service")]
    [System.SerializableAttribute()]
    public partial class Staff : ATS.Service.WCFClient.ATS.WCFClient.Person {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ATS.Service.WCFClient.ATS.WCFClient.Agent AgentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupervisorNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ATS.Service.WCFClient.ATS.WCFClient.Agent Agent {
            get {
                return this.AgentField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentField, value) != true)) {
                    this.AgentField = value;
                    this.RaisePropertyChanged("Agent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupervisorName {
            get {
                return this.SupervisorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupervisorNameField, value) != true)) {
                    this.SupervisorNameField = value;
                    this.RaisePropertyChanged("SupervisorName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ATSFault", Namespace="http://schemas.datacontract.org/2004/07/ATS.Service")]
    [System.SerializableAttribute()]
    public partial class ATSFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ATS.WCFClient.IPersonService")]
    public interface IPersonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetPerson", ReplyAction="http://tempuri.org/IPersonService/GetPersonResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATS.Service.WCFClient.ATS.WCFClient.ATSFault), Action="http://tempuri.org/IPersonService/GetPersonATSFaultFault", Name="ATSFault", Namespace="http://schemas.datacontract.org/2004/07/ATS.Service")]
        ATS.Service.WCFClient.ATS.WCFClient.Person GetPerson(int personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetPerson", ReplyAction="http://tempuri.org/IPersonService/GetPersonResponse")]
        System.Threading.Tasks.Task<ATS.Service.WCFClient.ATS.WCFClient.Person> GetPersonAsync(int personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetSupervisedStaffs", ReplyAction="http://tempuri.org/IPersonService/GetSupervisedStaffsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ATS.Service.WCFClient.ATS.WCFClient.ATSFault), Action="http://tempuri.org/IPersonService/GetSupervisedStaffsATSFaultFault", Name="ATSFault", Namespace="http://schemas.datacontract.org/2004/07/ATS.Service")]
        ATS.Service.WCFClient.ATS.WCFClient.Person[] GetSupervisedStaffs(int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetSupervisedStaffs", ReplyAction="http://tempuri.org/IPersonService/GetSupervisedStaffsResponse")]
        System.Threading.Tasks.Task<ATS.Service.WCFClient.ATS.WCFClient.Person[]> GetSupervisedStaffsAsync(int companyId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonServiceChannel : ATS.Service.WCFClient.ATS.WCFClient.IPersonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonServiceClient : System.ServiceModel.ClientBase<ATS.Service.WCFClient.ATS.WCFClient.IPersonService>, ATS.Service.WCFClient.ATS.WCFClient.IPersonService {
        
        public PersonServiceClient() {
        }
        
        public PersonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ATS.Service.WCFClient.ATS.WCFClient.Person GetPerson(int personId) {
            return base.Channel.GetPerson(personId);
        }
        
        public System.Threading.Tasks.Task<ATS.Service.WCFClient.ATS.WCFClient.Person> GetPersonAsync(int personId) {
            return base.Channel.GetPersonAsync(personId);
        }
        
        public ATS.Service.WCFClient.ATS.WCFClient.Person[] GetSupervisedStaffs(int companyId) {
            return base.Channel.GetSupervisedStaffs(companyId);
        }
        
        public System.Threading.Tasks.Task<ATS.Service.WCFClient.ATS.WCFClient.Person[]> GetSupervisedStaffsAsync(int companyId) {
            return base.Channel.GetSupervisedStaffsAsync(companyId);
        }
    }
}
