//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Supervisors = new HashSet<Supervisor>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyDescription { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Supervisor> Supervisors { get; set; }
    }
}
